jwt:
  secret: 76jr78jh6agegej56vhst456sf
  lifetime: 10m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: info
    org.springframework.web: info
  pattern:
    file: budget_tracker_app_logs.txt

